# Generated by Django 4.2.29 on 2026-03-22 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('level_required', models.IntegerField()),
                ('damage_effect', models.TextField()),
                ('usage_limit', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('spell', 'Spell'), ('ability', 'Ability')], max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PreparedSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared', models.BooleanField(default=True)),
                ('usage_remaining', models.IntegerField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_spells', to='campaign_manager.character')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_spells', to='campaign_manager.session')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparations', to='campaign_manager.spell')),
            ],
            options={
                'unique_together': {('character', 'spell', 'session')},
            },
        ),
        migrations.CreateModel(
            name='CharacterSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='campaign_manager.character')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_spells', to='campaign_manager.spell')),
            ],
            options={
                'unique_together': {('character', 'spell')},
            },
        ),
    ]
