# Generated by Django 4.2.29 on 2026-03-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0002_spell_preparedspell_characterspell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparedspell',
            name='prepared',
        ),
    ]
